### ISSUE TITLE
Static site and __STATIC_CONTENT_MANIFEST with test framework

### ISSUE THREAD

**Issue by rustymagnet3000** [honojs/examples#109]
The static example works great.

```javascript
import { Hono } from 'hono'

import { serveStatic } from 'hono/cloudflare-workers'
import manifest from '__STATIC_CONTENT_MANIFEST'

const app = new Hono()

app.get('/static/*', serveStatic({ root: './', manifest }))
app.use('/favicon.ico', serveStatic({ path: './favicon.ico', manifest  }))
app.get('/', (c) => c.text('This is Home! You can access: /static/fallback.txt'))

```

Is there a way to get `vitest` or `jest` to stop complaining about `__STATIC_CONTENT_MANIFEST`?

```
Error: Failed to load url __STATIC_CONTENT_MANIFEST (resolved id: __STATIC_CONTENT_MANIFEST) in foo.test.js. Does the file exist?
 ❯ loadAndTransform node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:53848:21
```

**Comment by yusukebe** [comment]
Hi @rustymagnet3000 

I've never tried with `__STATIC_CONTENT_MANIFEST` but how about using `@cloudflare/vitest-pool-workers`?

https://developers.cloudflare.com/workers/testing/vitest-integration/get-started/write-your-first-test/

**Comment by rustymagnet3000** [comment]
Thanks for all you do @yusukebe. 

At the moment I have solved it by using [JSX](https://hono.dev/guides/jsx) instead of the static site instructions.  I'll close the issue as I think the alternatives ( using JSX or the link you provided above ) are strong.

**Comment by yusukebe** [comment]
Hi @rustymagnet3000 

FYI. The serve static on Cloudflare **Workers** will be actually deprecated because [Worker Sites](https://developers.cloudflare.com/workers/configuration/sites/) that is used in the serve static is now deprecated. So, I recommend using Cloudflare Pages starter with the `npm create hono` command.
