### ISSUE TITLE
Blog2 examples which delivers html using data from postgres

### ISSUE THREAD

**Issue by rishavs** [honojs/examples#14]
@yusukebe , is there an interest in my adding another blog type web app in the examples folder? 

The current is api based, while the one I have renders html using simple interpolated strings. 
the app also uses postgres for the data.

**Comment by yusukebe** [comment]
Hi @rishavs !

Interesting, but it may be difficult to put it in this official repository. We can make the link from honojs.dev to your repository. By the way, what platform are you running it on? Bun? Deno? CF Workers?

**Comment by rishavs** [comment]
Its on Deno. and uses postgres.js for the drivers.
repo is at https://github.com/rishavs/hina
