### ISSUE TITLE
Misstake in ussage commands

### ISSUE THREAD

**Issue by YukiYuigishi** [honojs/examples#17]
I found a mistake in the usage commands.
This command does not work.

https://github.com/honojs/examples/blob/284f11c3e895bae359d68854a74998cf78ad43b6/blog/README.md?plain=1#L25-L27

```diff
-yarn run install
+yarn install 
```

**Comment by yusukebe** [comment]
Hi @YukiYuigishi !

I've fixed this issue. Thank you!
