### ISSUE TITLE
JSDoc Compatibility

### ISSUE THREAD

**Issue by JagritGumber** [honojs/examples#173]
I have been trying to use Hono and JsDoc Comments as JSDoc just improves how we use Javascript and is really helpful, I work on solo projects not someone who like typescript in that regards and using Cloudflare workers I have been encountering issues such as 

```
X [ERROR] Could not resolve "hono/dist/types"

    src/workers/handlers/Auth.Handler.js:4:24:
      4 │ import { Context } from "hono/dist/types";
        ╵                         ~~~~~~~~~~~~~~~~~

  The path "./dist/types" is not exported by package "hono":

    node_modules/hono/package.json:36:13:
      36 │   "exports": {
         ╵              ^

  The file "./dist/types.js" is exported at path "./types":

    node_modules/hono/package.json:44:16:
      44 │       "import": "./dist/types.js",
         ╵                 ~~~~~~~~~~~~~~~~~

  Import from "hono/types" to get the file "node_modules/hono/dist/types.js":

    src/workers/handlers/Auth.Handler.js:4:24:
      4 │ import { Context } from "hono/dist/types";
        │                         ~~~~~~~~~~~~~~~~~
        ╵                         "hono/types"

  You can mark the path "hono/dist/types" as external to exclude it from the bundle, which will remove this error.
  ```

When I do hono/types it rather goes on fetching hono/dist/types.js something I do not want
I would really like the support for JSDoc as I use it too much and this library is really helpful, Below attached output
```X [ERROR] No matching export in "node_modules/hono/dist/types.js" for import "Context"

    src/workers/handlers/Auth.Handler.js:4:9:
      4 │ import { Context } from "hono/types";
        ╵          ~~~~~~~
```
  
I would also be glad to know if somehow I can contribute to this repository in this regard if the feature is still not implemented, If it is I would be glad to know

**Comment by yusukebe** [comment]
Hi @JagritGumber 

Does it mean the problem is `context` is not imported as a class?

**Comment by JagritGumber** [comment]
Hi @yusukebe, it actually I think means that `Context` is not being exported and yes it means as a class, I went through the library and it is being exported in hono/types as a class so it is kind of confusing

**Comment by yusukebe** [comment]
@JagritGumber 

Understood well! I think it should be exported from `hono` not `hono/types`. This is a `hono` matter, so can you create an issue on https://github.com/honojs/hono/issues?

**Comment by JagritGumber** [comment]
Sure I will create an issue over there, but it is also not exported from hono when I tried, I will create issue over there, Idk how I came to examples.

**Comment by yusukebe** [comment]
@JagritGumber Thanks!
