### ISSUE TITLE
Can not get KVNamespace Bindings by c.env.XX in the jsx-ssr example

### ISSUE THREAD

**Issue by buzheng** [honojs/examples#18]
Hi, I'm newer to hono and cloudflare workers.  In the jsx-ssr example, I add some code to get value from the KV storage. 

A error happens:  `TypeError: Cannot read properties of undefined (reading 'get')`.

And I out put the  `c.env` and it is empty: `{}`.

Is there something wrong?

**Comment by yusukebe** [comment]
Hi @buzheng !

To get the value from `c.env`, use "Module Worker Mode".

<https://blog.cloudflare.com/workers-javascript-modules/>

```ts
// write below instead of `app.fire()`
export default app
```

**Comment by buzheng** [comment]
@yusukebe 

I changed it, and started the server, but there was still an error when requesting the home page:

```log
[mf:err] GET /: FetchError [ERR_NO_HANDLER]: No fetch handler defined and no upstream to proxy to specified.
Make sure you're calling addEventListener("fetch", ...).
```

**Comment by yusukebe** [comment]
Hmm, maybe the project setting is not good.

**Comment by buzheng** [comment]
@YukiYuigish,

I got a solution.

1. modify the index.tsx as you said:

    ```javascript
    // write below instead of `app.fire()`
    export default app
    ```

2. modify the build script in `package.json`, add `--format=esm`:

    ```javascript
    esbuild --bundle --outdir=dist --format=esm ./src/index.tsx
    ```

3. Start with the command `wrangler dev`.

Thanks for your help.
