### ISSUE TITLE
Replace hono-vite-jsx example with something that works

### ISSUE THREAD

**Issue by morgs32** [honojs/examples#218]
The hono-vite-jsx example is... not good. It doesn't use `hono client` and it is not "stackblitz friendly".
This one works much better and demonstrates how hono client works too:
https://github.com/yusukebe/hono-jsx-dom-with-vite/tree/main

**Comment by yusukebe** [comment]
Hi @morgs32 thank you for the issue.

Indeed, using Hono Client is good.

@MathurAditya724 What do you think of it?

**Comment by MathurAditya724** [comment]
Hey @morgs32, thanks for the feedback. I have some ideas to improve this example, including showing the usage of `hono/client`. I am thinking of using the `@hono/vite-dev-server` and `@hono/vite-build` for this example.

Can you explain a bit more, what do you mean by it's not stack blitz friendly?

**Comment by MathurAditya724** [comment]
@yusukebe, should I also refer this example in the `@hono/vite-build` repo once this is merged?
