### ISSUE TITLE
Hono Bun jsx displays [object Object] & jsxFactory not specified

### ISSUE THREAD

**Issue by mountainash** [honojs/examples#81]
From https://github.com/honojs/hono/issues/606 the issue is still valid

Tested with:
- Bun v0.5.8
- Huno v3.1.3
- TypeScript v4.9.5

1) The answer at https://github.com/honojs/hono/issues/606#issuecomment-1280063327 is valid and fixes the problem, but should be updated here in `/bun/tsconfig.json`

from: 
```json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxFragmentFactory": "Fragment",
    "jsxImportSource": "hono/jsx"
  }
}
```

to:

```json 
{
  "compilerOptions": {
    "jsx": "preserve",
    "jsxFragmentFactory": "Fragment",
    "jsxImportSource": "hono/jsx"
  }
}
```

2) there's a second issue that TypeScript errors with:

`Option 'jsxFragmentFactory' cannot be specified without specifying option 'jsxFactory'.`

Which can be solved by adding `"jsxFactory": "jsx",`

**Comment by eanp** [comment]
I’m encountering an issue where my app runs perfectly during development, but when I compile it for production, I get an error like this.
