### ISSUE TITLE
Next.js App Router

### ISSUE THREAD

**Issue by vhmartinezm** [honojs/examples#90]
@yusukebe Is it possible to use Hono with the new Next.js app directory? If so, do you have some example?

Thank you for your excellent work

**Comment by vhmartinezm** [comment]
@sizumita that was super helpful. Thanks!

**Comment by sizumita** [comment]
Related: https://twitter.com/honojs/status/1660582592385798145?s=20

**Comment by yusukebe** [comment]
I'll fix this issue. Thanks.

**Comment by masterbater** [comment]
> I'll fix this issue. Thanks.

Please add example for nextjs app router
