### ISSUE TITLE
Example with other cloudflare service 

### ISSUE THREAD

**Issue by thibaultleouay** [honojs/examples#98]
Hey,

I really like hono, and I'd love to see how I can use it with cloudflare queue ? And Cron ?

Maybe some simple example would be super nice 

A full example 

https://github.com/orgs/honojs/discussions/1163

**Comment by yusukebe** [comment]
Hi @thibaultleouay 

Thanks for loving Hono.

For Queue or Cron, I think there are not so much things we have to write. So it's better to add the documents to "Snippets" which is added recently.

https://hono.dev/snippets/top

cc: @sor4chi

**Comment by thibaultleouay** [comment]
That would be fantastic, 
 And it would also help me to better understand other cloudflare service 😁

**Comment by sor4chi** [comment]
```ts
import { Hono } from "hono";

type Environment = {
  readonly ERROR_QUEUE: Queue<Error>;
  readonly ERROR_BUCKET: R2Bucket;
};

const app = new Hono<{
  Bindings: Environment;
}>();

app.get("/", (c) => {
  if (Math.random() < 0.5) {
    return c.text("Success!");
  }
  throw new Error("Failed!");
});

app.onError(async (err, c) => {
  await c.env.ERROR_QUEUE.send(err);
  return c.text(err.message, { status: 500 });
});

export default {
  fetch: app.fetch,
  async queue(batch: MessageBatch<Error>, env: Environment): Promise<void> {
    let file = "";
    for (const message of batch.messages) {
      const error = message.body;
      file += error.stack || error.message || String(error);
      file += "\r\n";
    }
    await env.ERROR_BUCKET.put(`errors/${Date.now()}.log`, file);
  },
};
```

How about this snippets? This source completely works.

Source: https://developers.cloudflare.com/queues/examples/send-errors-to-r2/

**Comment by thibaultleouay** [comment]
@sor4chi  thanks it was exactly what i wanted to see 🔥

**Comment by sor4chi** [comment]
@yusukebe Should I create a PR to add this snippet?

**Comment by yusukebe** [comment]
@sor4chi 

Yes, please.

**Comment by yusukebe** [comment]
This can be closed. Thanks!
